version: '3.8'
services:
  db:
    image: postgres:13.0
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres-naheem
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: music-app-db
    networks:
      - music-app-net
  db-test:
    image: postgres:13.0
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: postgres-naheem
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: music-app-test-db
    networks:
       - music-app-net
networks:
  music-app-net: